library(shiny)
library(shinythemes)
library(shinyjs)
library(dygraphs)
source("data/simularGAS.R")
source("data/dcs_fk_estimation.R")
graphs <- readRDS("data/dygraphs_nasdaq.rds")
resul <- readRDS("data/resultados_betategarch_estimation.rds")
resul_novo <- readRDS("data/novos_modelos.rds")
ipc <- readRDS("data/ipc.rds")
bsm <- readRDS("data/out_turistas.rds")
turistas <- readRDS("data/turistas.rds")