library(shiny)
library(shinythemes)
library(shinyjs)
library(dygraphs)
source("data/simularGAS.R")
graphs <- readRDS("data/dygraphs_nasdaq.rds")
resul <- readRDS("data/resultados_betategarch_estimation.rds")
